test_node_cpp:
  ros__parameters:
    target_color: "BLUE"
    debug_base: true
    debug_identification: true
    debug_preprocessing: true
    max_angle_diff: 10.0
    min_length_ratio: 0.7
    min_x_diff_ratio: 0.75
    max_y_diff_ratio: 1.0
    max_distance_ratio: 0.8
    min_distance_ratio: 0.1

armor_plate_identification_node:
  ros__parameters:
  # camera_type: "mindvision"
    camera_type: "galaxy"
    target_color: "BLUE"
    debug_base: true
    debug_identification: true
    debug_preprocessing: false
    max_angle_diff: 10.0
    min_length_ratio: 0.6
    min_x_diff_ratio: 0.75
    max_y_diff_ratio: 1.0
    max_distance_ratio: 0.8
    min_distance_ratio: 0.1
